# Generated by Django 5.1.4 on 2026-06-05 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0004_backfill_instance_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price_kzt', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена, ₸')),
                ('period_days', models.PositiveIntegerField(default=30, verbose_name='Длительность периода, дней')),
                ('message_limit', models.PositiveIntegerField(blank=True, help_text='Пусто = безлимит', null=True, verbose_name='Лимит сообщений за период')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='Фичи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['price_kzt'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Пробный период'), ('active', 'Активна'), ('past_due', 'Просрочена (грейс-период)'), ('suspended', 'Приостановлена'), ('canceled', 'Отменена')], db_index=True, default='trialing', max_length=16, verbose_name='Статус')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало периода')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Конец периода')),
                ('trial_end', models.DateTimeField(blank=True, null=True, verbose_name='Конец пробного периода')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='clinics.clinic', verbose_name='Клиника')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kzt', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма, ₸')),
                ('provider', models.CharField(default='manual', max_length=32, verbose_name='Провайдер')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID у провайдера')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Не прошёл')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('period_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало периода')),
                ('period_end', models.DateTimeField(blank=True, null=True, verbose_name='Конец периода')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clinics.clinic', verbose_name='Клиника')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.plan', verbose_name='Тариф')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(max_length=64, verbose_name='Ключ периода')),
                ('event_type', models.CharField(choices=[('reminder_3d', 'Напоминание за 3 дня'), ('reminder_1d', 'Напоминание за 1 день'), ('expired_suspend', 'Приостановка по окончании'), ('period_renewed', 'Период продлён')], max_length=32, verbose_name='Тип события')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='billing.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Событие биллинга',
                'verbose_name_plural': 'События биллинга',
                'ordering': ['-created_at'],
                'unique_together': {('subscription', 'period_key', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(verbose_name='Начало периода')),
                ('period_end', models.DateTimeField(verbose_name='Конец периода')),
                ('messages_in', models.PositiveIntegerField(default=0, verbose_name='Входящих сообщений')),
                ('messages_out', models.PositiveIntegerField(default=0, verbose_name='Исходящих сообщений')),
                ('ai_calls', models.PositiveIntegerField(default=0, verbose_name='Вызовов AI')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_counters', to='clinics.clinic', verbose_name='Клиника')),
            ],
            options={
                'verbose_name': 'Счётчик потребления',
                'verbose_name_plural': 'Счётчики потребления',
                'ordering': ['-period_start'],
                'unique_together': {('clinic', 'period_start')},
            },
        ),
    ]
