# Generated by Django 5.1.4 on 2026-06-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_plans_and_backfill_trials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingeventlog',
            name='event_type',
            field=models.CharField(choices=[('reminder_3d', 'Напоминание за 3 дня'), ('reminder_1d', 'Напоминание за 1 день'), ('expired_suspend', 'Приостановка по окончании'), ('period_renewed', 'Период продлён'), ('limit_reached', 'Лимит сообщений превышен')], max_length=32, verbose_name='Тип события'),
        ),
    ]
