# Generated by Django 5.1.4 on 2026-06-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_billingeventlog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingeventlog',
            name='event_type',
            field=models.CharField(choices=[('reminder_3d', 'Напоминание за 3 дня'), ('reminder_1d', 'Напоминание за 1 день'), ('expired_suspend', 'Приостановка по окончании'), ('period_renewed', 'Период продлён'), ('limit_reached', 'Лимит сообщений превышен'), ('owner_limit_alert', 'Владелец уведомлён о лимите')], max_length=32, verbose_name='Тип события'),
        ),
    ]
