# Generated by Django 5.1.4 on 2026-06-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('whatsapp_number', models.CharField(help_text='Номер-получатель в формате E.164, по нему определяется клиника', max_length=32, unique=True, verbose_name='Номер WhatsApp')),
                ('services_json', models.JSONField(blank=True, default=list, verbose_name='Услуги и цены')),
                ('working_hours', models.JSONField(blank=True, default=dict, verbose_name='Часы работы')),
                ('address', models.CharField(blank=True, max_length=512, verbose_name='Адрес')),
                ('tone', models.TextField(blank=True, default='Дружелюбный, вежливый, на «вы». Информируем, не продаём агрессивно.', verbose_name='Тон общения')),
                ('faq', models.JSONField(blank=True, default=list, verbose_name='FAQ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
                'ordering': ['name'],
            },
        ),
    ]
