# Generated by Django 5.1.4 on 2026-06-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='manager_whatsapp',
            field=models.CharField(blank=True, help_text='Номер админа клиники (E.164) для уведомлений о заявках на запись', max_length=32, null=True, verbose_name='WhatsApp менеджера'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Уведомления о заявках включены'),
        ),
    ]
