# Generated by Django 5.1.4 on 2026-06-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_clinicuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='hours_by_day',
            field=models.JSONField(blank=True, default=dict, help_text='Машиночитаемо: {"mon": ["09:00","20:00"], ..., "sun": null}. null = выходной. Источник правды для проверки времени записи.', verbose_name='Часы работы (по дням, для валидации)'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, verbose_name='Часы работы (текст)'),
        ),
    ]
