# Generated by Django 5.1.4 on 2026-06-02 17:20

import django.db.models.deletion
import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(db_index=True, max_length=32, verbose_name='Телефон пациента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='clinics.clinic', verbose_name='Клиника')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
                'ordering': ['-updated_at'],
                'unique_together': {('clinic', 'customer_phone')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пациент'), ('assistant', 'Бот'), ('system', 'Система')], max_length=16, verbose_name='Роль')),
                ('content', fernet_fields.fields.EncryptedTextField(verbose_name='Текст сообщения')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID у провайдера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation', verbose_name='Диалог')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
    ]
