# Generated by Django 5.1.4 on 2026-06-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='booking_draft',
            field=models.JSONField(blank=True, default=dict, verbose_name='Черновик заявки'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='booking_stage',
            field=models.CharField(choices=[('none', 'Нет записи'), ('collecting', 'Собираем данные'), ('ready', 'Готово к передаче менеджеру')], default='none', max_length=16, verbose_name='Стадия записи'),
        ),
    ]
