# Generated by Django 5.1.4 on 2026-06-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_clinic_and_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='suspended_notice_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее уведомление о недоступности'),
        ),
    ]
