# Generated by Django 5.1.4 on 2026-06-05 21:41

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_conversation_suspended_notice_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='booking_draft',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='booking_stage',
        ),
        migrations.AddField(
            model_name='conversation',
            name='booking_date_iso',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Дата записи (YYYY-MM-DD)'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='booking_name',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=128, null=True, verbose_name='Имя для записи'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='booking_service',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Услуга (слот записи)'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='booking_state',
            field=models.CharField(choices=[('idle', 'Запись не ведётся'), ('collecting', 'Собираем данные'), ('awaiting_confirmation', 'Ждём подтверждения')], db_index=True, default='idle', max_length=24, verbose_name='Состояние записи'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='booking_time',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Время записи (HH:MM)'),
        ),
    ]
