# Generated by Django 5.1.4 on 2026-06-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_remove_conversation_booking_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='booking_slot',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Текущий спрашиваемый слот'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='booking_slot_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Попыток по слоту подряд'),
        ),
    ]
