# Generated by Django 5.1.4 on 2026-06-04 08:59

import django.db.models.deletion
import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_clinic_manager_whatsapp_clinic_notifications_enabled'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', fernet_fields.fields.EncryptedCharField(max_length=32, verbose_name='Телефон пациента')),
                ('customer_name', fernet_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Имя пациента')),
                ('service', models.CharField(blank=True, max_length=255, verbose_name='Услуга')),
                ('preferred_date_raw', models.CharField(blank=True, max_length=255, verbose_name='Желаемая дата (как сказал)')),
                ('preferred_time_raw', models.CharField(blank=True, max_length=255, verbose_name='Желаемое время (как сказал)')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='Желаемая дата')),
                ('preferred_time', models.TimeField(blank=True, null=True, verbose_name='Желаемое время')),
                ('status', models.CharField(choices=[('new', 'Собрана (не отправлена менеджеру)'), ('notified', 'Менеджер уведомлён'), ('confirmed', 'Менеджер подтвердил'), ('rejected', 'Отклонена / предложено другое время'), ('cancelled', 'Отменена пациентом')], db_index=True, default='new', max_length=16, verbose_name='Статус')),
                ('manager_note', models.TextField(blank=True, null=True, verbose_name='Заметка менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='clinics.clinic', verbose_name='Клиника')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='messaging.conversation', verbose_name='Диалог')),
            ],
            options={
                'verbose_name': 'Заявка на запись',
                'verbose_name_plural': 'Заявки на запись',
                'ordering': ['-created_at'],
            },
        ),
    ]
